apiVersion: v2
name: grafana
version: 0.0.0
dependencies:
  - name: pvc
    version: 0.0.0
    repository: file://../../charts/pvc
  - name: grafana
    version: 10.4.1
    repository: oci://ghcr.io/grafana/helm-charts
