ingress:
  className: ""
  host: ""
  prefix: /oauth2

oidc:
  issuerURL: "https://auth.neils.house"
  allowedGroups:
    - admin
  clientID: ""
  clientSecretKey: ""
  cookieSecretKey: ""

nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 2000
  runAsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
