apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "pgcluster.instanceName" . }}
spec:
  cluster:
    name: {{ include "pgcluster.instanceName" . }}
  suspend: {{ or (.Values.recovery.enabled) (not .Values.backup.enabled) }}
  schedule: {{ .Values.backup.schedule | quote }}
  immediate: true
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
