apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: {{ required "clientSecret key is required" .Values.oidc.clientSecretKey }}
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: {{ required "cookieSecret key is required" .Values.oidc.cookieSecretKey }}
