pvc:
  pvcName: seerr-data
  storageRequest: 128Mi

app-template:
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  controllers:
    seerr:
      containers:
        seerr:
          image:
            repository: ghcr.io/seerr-team/seerr
            tag: v3.1.0@sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
  service:
    seerr:
      controller: seerr
      ports:
        http:
          port: 5055
  ingress:
    seerr:
      className: external
      hosts:
        - host: requests.neils.house
          paths:
            - path: /
              service:
                identifier: seerr
                port: http
  persistence:
    config:
      existingClaim: seerr-data
      globalMounts:
        - path: /app/config
